repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
        stages: [manual]
    -   id: check-added-large-files
        args: ['--maxkb=25000']
        stages: [manual]
    -   id: check-merge-conflict
        stages: [manual]
    -   id: check-yaml
        stages: [manual]
    -   id: debug-statements
        stages: [manual]
    -   id: end-of-file-fixer
        stages: [manual]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [manual]
    -   id: no-commit-to-branch
        args: ['--branch', 'main']
        stages: [manual]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
        stages: [manual]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    -   id: ruff
        args: [--fix]
        stages: [manual]
    -   id: ruff-format
        stages: [manual]
